name: Build-NanoPi-R1S-H5

on: 
  release:
    types: [published]

  #push:
  #  branches: 
  #    - master

  #schedule:
  #  - cron: 0 8 * * 5
  
  #watch:
  #  types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          hhvm \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex node-uglify gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx-ucl libelf-dev autoconf automake libtool autopoint device-tree-compiler libuv-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get -y install bc
        sudo -E apt-get -y install device-tree-compiler
        sudo -E apt-get -y install u-boot-tools
        sudo -E apt-get clean
        
    - name: Install Repo
      run: |
        git clone https://github.com/friendlyarm/repo
        sudo cp repo/repo /usr/bin/
          
    - name: Download Source
      run: |
        mkdir friendlywrt-h5
        cd friendlywrt-h5
        repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master -m h5.xml --repo-url=https://github.com/friendlyarm/repo  --no-clone-bundle
        repo sync -c  --no-clone-bundle
        git clone https://github.com/coolsnowwolf/lede
        cd friendlywrt
        cp -r ../lede/package/lean package/
        rm -rf feeds.conf.default
        cp -r ../lede/feeds.conf.default ../friendlywrt/
          
    - name: Update Target.mk
      run: |
        cd friendlywrt-h5/friendlywrt/include 
        sed -i 's/dnsmasq /dnsmasq-full default-settings luci/' target.mk
    
    - name: Update Feeds
      run: |
        cd friendlywrt-h5/friendlywrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
          
    - name: Costom Configure File
      run: |
        cd friendlywrt-h5/friendlywrt
        rm -f ./.config*
        wget https://github.com/lxpcwl/AutoBuild-OpenWrt/blob/master/NanoPi-R1S-H5.config
        cp NanoPi-R1S-H5.config .config
          
    - name: Build OpenWrt
      run: |
        cd friendlywrt-h5
        ./build.sh nanopi_r1s.mk
      
    - name: Zip Files
      run: |
        find friendlywrt-h5/out/ -name "FriendlyWrt_*img*" | xargs -i zip -r {}.zip {}
          
    - name: Assemble Artifact
      run: |
        rm -rf ./artifact/
        mkdir -p ./artifact/
        find friendlywrt-h5/out/ -name "FriendlyWrt_*img.zip*" | xargs -i mv -f {} ./artifact/
    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
          name: FriendlyWrt_NanoPi-R1S H5
          path: ./artifact/
