name: N1

on: 
  release:
    types: [published]

  #push:
  #  branches: 
  #    - master

  #schedule:
  #  - cron: 0 8 * * 5
  
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get update
        sudo -E apt-get -y install pigz
      
    - name: Create a directory
      run: |
        mkdir -p /opt/imgs/docker
        mkdir -p /opt/docker
        
    - name: download file
      run: |
        cd /opt/docker
        wget https://github.com/lxpcwl/AutoBuild-OpenWrt/raw/master/make_opwrt_docker_img.tar.gz
        wget https://github.com/lxpcwl/AutoBuild-OpenWrt/blob/master/openwrt-armvirt-64-default-rootfs.tar.gz
        
    - name: unzip files & Run build.sh
      run: |
        cd /opt/docker
        tar xvf make_opwrt_docker_img.tar.gz
        ./build.sh R20.3.7
        
    - name: Assemble Artifact
      run: |
        rm -rf ./artifact/
        mkdir -p ./artifact/
        find opt/imgs/docker/docker-img-openwrt-aarch64-R20.3.7.gz ./artifact/
        
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: docker-img-openwrt-aarch64
        path: ./artifact/
