name: R1S-H5

#on: 
  release:
    types: [published]

  #push:
  #  branches: 
  #    - master

  #schedule:
  #  - cron: 0 8 * * 5
  
  #watch:
  #  types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d
        sudo apt-get update
        sudo apt-get -y install bc build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
        wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk
        
    - name: Install repo
      run: |
        git clone https://github.com/friendlyarm/repo
        sudo cp repo/repo /usr/bin/
        
    - name: Clone source code
      run: |
        mkdir friendlywrt-h5
        cd friendlywrt-h5
        repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master -m h5.xml --repo-url=https://github.com/friendlyarm/repo --no-clone-bundle
        repo sync -c --no-clone-bundle -j8
        
    - name: Merge lede
      run: |
        git clone https://github.com/coolsnowwolf/lede
        cp -r ./lede/package/lean ./friendlywrt-h5/friendlywrt/package
    
    - name: SSH connection to Actions
      uses: P3TERX/debugger-action@master
      
    - name: Update & Install feeds
      run: |
        cd friendlywrt-h5/friendlywrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        ./scripts/feeds install -a
      
    - name: Configuration Customization - R1S-H5
      env:
        CONFIG_FILE: 'R1S-H5.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE friendlywrt-h5/friendlywrt/.config
        cd friendlywrt-h5/friendlywrt && make defconfig
        
    - name: Download package
      if: always()
      run: |
        cd friendlywrt-h5/friendlywrt
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        
    - name: Compile the firmware
      run: |
        cd friendlywrt-h5
        ./build.sh nanopi_r1s.mk
        
    - name: Compressed file
      run: |
        find friendlywrt-h5/out/ -name "FriendlyWrt_*img*" | xargs -i zip -r {}.zip {}
        
    - name: Assemble artifact
      run: |
        rm -rf ./artifact/
        mkdir -p ./artifact/
        find friendlywrt-h5/out/ -name "FriendlyWrt_*img.zip*" | xargs -i mv -f {} ./artifact/
        
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: R1S-H5
        path: ./artifact/
